
//GET ALL proyects
GET http://localhost:3001/proyects
content-type: application/json


###

//GET proyect by AdminProyect and ProyectName

GET http://localhost:3001/proyects/sicard6/MyProyect
content-type: application/json


###

//GET proyect by user

GET http://localhost:3001/proyects/david55
content-type: application/json

###

//POST Proyect

POST http://localhost:3001/proyects
content-type: application/json

    {
    "ProyectName":"MyProyect2",
    "AdminProyect":"sicard6",
    "Associates":[],
    "TaskBoards":[]
    }

###

//DELETE Proyect By nameProyect and AdminProyect
///:AdminProyect/:proyectName
DELETE http://localhost:3001/proyects/sicard6/MyProyect2
content-type: application/json


###

//PUT add TaskBoard given the AdminProyect and the ProyectName
///:AdminProyect/:proyectName/addTaskBoard

PUT http://localhost:3001/proyects/sicard6/MyProyect2/addTaskBoard
content-type: application/json

    {
        "name": "hola",
        "Tasks": []
    }

###

//PUT DELETE TaskBoard given the AdminProyect and the ProyectName
///:AdminProyect/:proyectName/DeleteTaskBoard/:name

PUT http://localhost:3001/proyects/sicard6/MyProyect2/DeleteTaskBoard/hola2
content-type: application/json

###

//PUT add Assosiate given the AdminProyect and the ProyectName
///:AdminProyect/:proyectName/addAssociate/:associate

PUT http://localhost:3001/proyects/sicard6/MyProyect2/addAssociate/david55
content-type: application/json

###

//PUT delete Assosiate given the AdminProyect and the ProyectName
///:AdminProyect/:proyectName/deleteAssociate/:associate
PUT http://localhost:3001/proyects/sicard6/MyProyect2/deleteAssociate/david55
content-type: application/json

###

//PUT add task given the AdminProyect, the ProyectName and the index of the taskBoard
///:AdminProyect/:proyectName/addTask/:TaskBoardIndex
PUT http://localhost:3001/proyects/sicard6/MyProyect2/addTask/0
content-type: application/json
    
    {
        "name": "TaskTest",
        "description": "descriptionTest",
        "onCharge":[],
        "timeSpent":[]
    }
###

//PUT Delete task given the AdminProyect, the ProyectName, the index of the taskBoard and the index of the task
///:AdminProyect/:proyectName/deletetask/:TaskBoardIndex/:TaskIndex

PUT http://localhost:3001/proyects/sicard6/MyProyect2/deletetask/0/0
content-type: application/json

###

//PUT Assign task given the AdminProyect, the ProyectName, the index of the taskBoard and the index of the task
///:AdminProyect/:proyectName/:TaskBoardIndex/:TaskIndex/assign/:name
PUT http://localhost:3001/proyects/sicard6/MyProyect2/0/0/assign/lucas
content-type: application/json

###

//PUT add time to a task given the AdminProyect, proyectName, TaskBoardIndex and TaskIndex.
//if there is already a user with time on that task, it will add the time passed on the body.
///:AdminProyect/:proyectName/:TaskBoardIndex/:TaskIndex/addTime

PUT http://localhost:3001/proyects/sicard6/MyProyect2/0/0/addTime
content-type: application/json

    {
        "UserName": "andres",
        "timeSec": 1200
    }








