
//GET ALL proyects
GET http://localhost:3001/proyects
content-type: application/json


###

//GET proyect by AdminProyect and ProyectName

GET http://localhost:3001/proyects/sicard6/MyProyect
content-type: application/json


###

//GET proyect by AdminProyect

GET http://localhost:3001/proyects/sicard6
content-type: application/json
